spring:
  datasource:
    username: postgres
    password: Wy754inp0#
    url: jdbc:postgresql://localhost:5432/pwmanager
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database: POSTGRESQL
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

logging:
  level:
    root:  info
    org:
      springframework: info
      hibernate: info
      apache: info