spring:
  datasource:
    username: postgres
    password: Wy754inp0#
    url: jdbc:postgresql://localhost:5432/pwmanager
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        format_sql: true
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: "e714e2f007f514"
    password: "8dadb8a35e01a4"
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root:  info
    org:
      springframework:
        security:
          web:
            FilterChainProxy: Debug
      hibernate: info
      apache: info