spring:
  datasource:
    username: oorntmzktyoxem
    password: fe2c223652d4428cd4f236f0e4a918cf16589be052ceb0ca1745b2a85d23a6a5
    url: jdbc:postgresql://ec2-63-32-248-14.eu-west-1.compute.amazonaws.com:5432/d35f8dlmon68qj
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
    show-sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

logging:
  level:
    root: info
    org:
      springframework: info
      hibernate: info
      apache: info
      
server:
  tomcat:
    remoteip:
      remote-ip-header: "x-forwarded-for"
      protocol-header: "x-forwarded-proto"